from __future__ import annotations

from typing import Protocol

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.auth import User
from app.models.profile import CustomerProfile, CustomerRiskAssessment, Product


class CustomerRepository(Protocol):
    async def get_user(self, session: AsyncSession, user_id: str) -> User | None: ...
    async def get_profile(self, session: AsyncSession, user_id: str) -> CustomerProfile | None: ...
    async def save_profile(self, session: AsyncSession, profile: CustomerProfile) -> CustomerProfile: ...

class ProductRepository(Protocol):
    async def get_active(self, session: AsyncSession, product_id: str) -> Product | None: ...
    async def list_active(self, session: AsyncSession) -> list[Product]: ...

class RiskAssessmentRepository(Protocol):
    async def get_active(self, session: AsyncSession, user_id: str) -> CustomerRiskAssessment | None: ...
    async def supersede_active(self, session: AsyncSession, user_id: str) -> None: ...
    async def save(self, session: AsyncSession, assessment: CustomerRiskAssessment) -> CustomerRiskAssessment: ...
