from typing import Protocol

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.profile import CustomerAssetSnapshot, CustomerHolding
from app.models.trading import Account, Order


class AccountRepository(Protocol):
    async def get_by_user(self, session: AsyncSession, user_id: str, for_update: bool = False) -> Account | None: ...
    async def save(self, session: AsyncSession, account: Account) -> Account: ...

class OrderRepository(Protocol):
    async def get(self, session: AsyncSession, order_id: str, user_id: str | None = None, for_update: bool = False) -> Order | None: ...
    async def get_by_idempotency(self, session: AsyncSession, user_id: str, key: str) -> Order | None: ...
    async def save(self, session: AsyncSession, order: Order) -> Order: ...

class HoldingRepository(Protocol):
    async def get_active(self, session: AsyncSession, user_id: str, product_id: str, for_update: bool = False) -> CustomerHolding | None: ...
    async def sum_market_value(self, session: AsyncSession, user_id: str): ...
    async def save(self, session: AsyncSession, holding: CustomerHolding) -> CustomerHolding: ...

class AssetRepository(Protocol):
    async def latest(self, session: AsyncSession, user_id: str) -> CustomerAssetSnapshot | None: ...
    async def save(self, session: AsyncSession, snapshot: CustomerAssetSnapshot) -> CustomerAssetSnapshot: ...
