<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { tradingApi } from '../api/trading'
const orders=ref<any[]>([]); const trades=ref<any[]>([]); const account=ref<any>(null); const loading=ref(true); const error=ref('')
const statusText:Record<string,string>={pending_confirmation:'待确认',pending_review:'待审核',executing:'执行中',executed:'已完成',rejected:'已拒绝',cancelled:'已取消'}
async function load(){try{account.value=(await tradingApi.account()).data.data;orders.value=(await tradingApi.orders()).data.data; trades.value=(await tradingApi.trades()).data.data}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function confirm(id:string){await tradingApi.confirm(id);await load()}async function cancel(id:string){await tradingApi.cancel(id);await load()}
onMounted(load)
</script>
<template><section class="table-module"><div class="module-header"><div><span class="module-kicker">CUSTOMER ORDERS</span><h2>我的订单</h2></div><span class="table-summary">可用余额 ¥{{account?.available_balance??0}}</span></div><p v-if="error" class="error">{{error}}</p><div v-if="loading" class="empty">正在读取订单…</div><div v-else class="module-table-wrap"><table class="admin-table"><thead><tr><th>订单号</th><th>产品</th><th>金额</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="order in orders" :key="order.id"><td>{{order.order_no}}</td><td>{{order.product_name||order.product_id}}</td><td>¥{{order.amount}}</td><td>{{statusText[order.status]||order.status}}</td><td>{{order.created_at}}</td><td><button v-if="order.status==='pending_confirmation'" class="table-action" @click="confirm(order.id)">确认</button><button v-if="['pending_confirmation','pending_review'].includes(order.status)" class="table-action danger" @click="cancel(order.id)">取消</button></td></tr><tr v-if="!orders.length"><td colspan="6" class="table-empty">暂无订单</td></tr></tbody></table></div><div class="admin-section-heading"><h3>交易记录</h3><span class="table-summary">已执行</span></div><div class="module-table-wrap"><table class="admin-table"><thead><tr><th>交易号</th><th>订单号</th><th>金额</th><th>数量</th><th>执行时间</th></tr></thead><tbody><tr v-for="trade in trades" :key="trade.id"><td>{{trade.trade_no}}</td><td>{{trade.order_id}}</td><td>¥{{trade.amount}}</td><td>{{trade.quantity}}</td><td>{{trade.executed_at}}</td></tr><tr v-if="!trades.length"><td colspan="5" class="table-empty">暂无交易记录</td></tr></tbody></table></div></section></template>
