<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { profileApi } from '../api/profile'
import { tradingApi } from '../api/trading'
import { useAuth } from '../stores/auth'
const products=ref<any[]>([]);const loading=ref(true);const auth=useAuth();const selected=ref<any>(null);const amount=ref(0);const message=ref('');const error=ref('');const risk=ref<any>(null);const riskOrder:Record<string,number>={C1:1,C2:2,C3:3,C4:4,C5:5,R1:1,R2:2,R3:3,R4:4,R5:5}
onMounted(async()=>{try{products.value=(await profileApi.products()).data.data;if(auth.loggedIn.value) risk.value=(await profileApi.riskAssessment()).data.data}catch{}finally{loading.value=false}})
function productBlocked(product:any){const level=riskOrder[product.risk_level]||1;const current=riskOrder[risk.value?.risk_level||'C1']||1;return level>current}
function productHint(product:any){if(product.target_customer_type==='enterprise'&&risk.value?.customer_type!=='enterprise')return '仅限企业客户';if(productBlocked(product))return risk.value?'需完成更高风险等级测评':'请先完成风险测评';return ''}
async function submit(){if(!selected.value)return;try{error.value='';await tradingApi.createOrder({product_id:selected.value.id,amount:Number(amount.value)});message.value='订单已创建，请前往我的订单确认';selected.value=null}catch(e:any){error.value=(e as Error).message}}
</script>
<template><section><div class="section-heading"><div><span class="eyebrow">PRODUCT MARKET</span><h2>产品展示</h2><p>精选财富管理产品，具体条款以产品说明书及正式文件为准。</p></div><span class="pill">产品中心</span></div><div v-if="loading" class="empty">正在读取产品目录…</div><div v-else class="dashboard-grid"><article v-for="product in products" :key="product.id" class="dashboard-card"><span class="card-kicker">{{product.risk_level}} · {{product.product_type}}</span><h3>{{product.name}}</h3><p>{{product.description}}</p><small>起购金额：¥{{product.minimum_amount}} · 期限：{{product.term_days ? product.term_days + '天' : '开放期限（随时申赎）'}}</small><button v-if="auth.loggedIn.value" class="card-link text-button" :disabled="!!productHint(product)" :title="productHint(product)" @click="selected=product;amount=product.minimum_amount">{{productHint(product)||'立即购买 →'}}</button><RouterLink v-else class="card-link" to="/login">登录后操作 →</RouterLink></article></div><p v-if="message" class="success">{{message}}</p><p v-if="error" class="error">{{error}}</p><div v-if="selected" class="auth-card trade-modal"><span class="eyebrow">NEW ORDER</span><h3>购买 {{selected.name}}</h3><label>购买金额<input v-model.number="amount" type="number" :min="selected.minimum_amount" /></label><div class="action-row"><button class="button" @click="submit">创建交易申请</button><button class="text-button" @click="selected=null">取消</button></div></div></section></template>
