<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { authApi } from '../api/auth'
import { roleLabel } from '../constants/roles'
const router=useRouter(); const registerType=ref<'customer'|'employee'>('customer'); const username=ref(''); const password=ref(''); const displayName=ref(''); const companyCode=ref(''); const error=ref(''); const message=ref(''); const loading=ref(false); const isEmployee=computed(()=>registerType.value==='employee')
async function register(){loading.value=true;error.value='';message.value='';try{const r=await authApi.register({register_type:registerType.value,username:username.value,password:password.value,display_name:displayName.value,company_code:isEmployee.value?companyCode.value:undefined});message.value=`注册成功，当前角色：${roleLabel(r.data.data.role)}。请返回登录。`;username.value='';password.value='';companyCode.value=''}catch(e:any){error.value=e.message}finally{loading.value=false}}
</script>
<template><section class="auth-page"><div class="auth-card"><span class="eyebrow">CREATE ACCOUNT</span><h2>注册账号</h2><p>客户无需公司码；员工注册需要公司固定公司码，注册后暂为待分组员工。</p><form @submit.prevent="register"><div class="type-switch"><button type="button" :class="{active:registerType==='customer'}" @click="registerType='customer'">客户注册</button><button type="button" :class="{active:registerType==='employee'}" @click="registerType='employee'">员工注册</button></div><label>显示名称<input v-model="displayName" required /></label><label>账号<input v-model="username" autocomplete="username" required /></label><label>密码<input v-model="password" type="password" autocomplete="new-password" minlength="8" required /></label><label v-if="isEmployee">公司码<input v-model="companyCode" required /></label><p v-if="error" class="error">{{ error }}</p><p v-if="message" class="success">{{ message }}</p><button class="button" :disabled="loading">{{loading?'注册中…':'注册'}}</button></form><button class="text-button" @click="router.push('/login')">已有账号？返回登录</button></div></section></template>
