<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { profileApi } from '../api/profile'
import PaginationBar from '../components/PaginationBar.vue'
const products=ref<any[]>([]);const detail=ref<any|null>(null);const total=ref(0);const page=ref(1);const pageSize=ref(10);const query=ref('');const status=ref('active');const loading=ref(false);const error=ref('');const editing=ref<any|null>(null);const showForm=ref(false);const form=ref<any>(emptyProduct());const pages=computed(()=>Math.max(1,Math.ceil(total.value/pageSize.value)))
function emptyProduct(){return{name:'',product_type:'fund',risk_level:'C1',term_days:0,minimum_amount:0,liquidity:'medium',description:'',status:'active'}}
async function load(){loading.value=true;error.value='';try{const response=await profileApi.staffProducts(query.value,status.value,pageSize.value,(page.value-1)*pageSize.value);products.value=response.data.data.items;total.value=response.data.data.total}catch(e:any){error.value=e.response?.data?.detail||e.message}finally{loading.value=false}}
function openDetail(product:any){detail.value=product}function openCreate(){editing.value=null;form.value=emptyProduct();showForm.value=true}function openEdit(product:any){editing.value=product;form.value={...product};showForm.value=true}function close(){editing.value=null;form.value=emptyProduct();showForm.value=false}
async function save(){try{if(editing.value)await profileApi.updateProduct(editing.value.id,form.value);else await profileApi.createProduct(form.value);close();await load()}catch(e:any){error.value=e.response?.data?.detail||e.message}}
async function removeProduct(product:any){if(!window.confirm('确认软删除该产品？'))return;try{await profileApi.deleteProduct(product.id);await load()}catch(e:any){error.value=e.response?.data?.detail||e.message}}
async function restoreProduct(product:any){try{await profileApi.restoreProduct(product.id);await load()}catch(e:any){error.value=e.response?.data?.detail||e.message}}
function go(next:number){page.value=Math.min(Math.max(next,1),pages.value);load()}function changeSize(size:number){pageSize.value=size;page.value=1;load()}onMounted(load)
</script>
<template><section class="table-module"><div class="module-header"><div><span class="module-kicker">PRODUCT MANAGEMENT</span><h2>产品管理</h2></div><button class="button" @click="openCreate">新增产品</button></div><div class="module-tools"><input v-model="query" placeholder="搜索产品名称或类型" @keyup.enter="page=1;load()"/><select v-model="status" @change="page=1;load()"><option value="active">正常产品</option><option value="deleted">回收站</option><option value="all">全部产品</option></select><button class="table-action" @click="page=1;load()">搜索</button></div><p v-if="error" class="error">{{error}}</p><div v-if="loading" class="empty">正在读取产品…</div><div v-else class="module-table-wrap"><table class="admin-table"><thead><tr><th>产品名称</th><th>类型</th><th>风险等级</th><th>期限</th><th>起购金额</th><th>流动性</th><th>状态</th><th>创建时间</th><th>修改时间</th><th>删除时间</th><th>操作</th></tr></thead><tbody><tr v-for="product in products" :key="product.id"><td>{{product.name}}</td><td>{{product.product_type}}</td><td><span class="table-tag">{{product.risk_level}}</span></td><td>{{product.term_days}} 天</td><td>¥{{product.minimum_amount}}</td><td>{{product.liquidity}}</td><td>{{product.status==='deleted'?'已删除':(product.status==='active'?'启用':'停用')}}</td><td>{{product.created_at}}</td><td>{{product.updated_at}}</td><td>{{product.deleted_at || '-'}}</td><td><button v-if="product.status!=='deleted'" class="table-action" @click="openEdit(product)">编辑</button><button v-if="product.status!=='deleted'" class="table-action danger" @click="removeProduct(product)">删除</button><button v-else class="table-action" @click="restoreProduct(product)">恢复</button></td></tr><tr v-if="!products.length"><td colspan="11" class="table-empty">暂无产品</td></tr></tbody></table></div><PaginationBar :page="page" :page-size="pageSize" :total="total" @change="go" @size-change="changeSize"/><div v-if="showForm" class="admin-modal-backdrop" @click.self="close"><div class="admin-modal product-editor-modal"><div class="modal-header"><div><span class="module-kicker">PRODUCT EDITOR</span><h3>{{editing?'编辑产品':'新增产品'}}</h3></div><button class="modal-close" @click="close">×</button></div><div class="product-editor-grid"><label>产品名称<input v-model="form.name"/></label><label>产品类型<input v-model="form.product_type"/></label><label>风险等级<select v-model="form.risk_level"><option>C1</option><option>C2</option><option>C3</option><option>C4</option><option>C5</option></select></label><label>期限（天）<input v-model.number="form.term_days" type="number" min="0"/></label><label>起购金额<input v-model.number="form.minimum_amount" type="number" min="0"/></label><label>流动性<input v-model="form.liquidity"/></label><label>状态<select v-model="form.status"><option value="active">启用</option><option value="inactive">停用</option></select></label><label class="full">产品描述<textarea v-model="form.description"/></label></div><div class="action-row"><button class="button" @click="save">保存</button><button class="text-button" @click="close">取消</button></div></div></div></section></template>


