<script setup lang="ts">
import { onMounted, ref, computed } from 'vue'
import { profileApi } from '../api/profile'
import { tradingApi } from '../api/trading'
import PaginationBar from '../components/PaginationBar.vue'
import ProfileEnhancedView from './ProfileEnhancedView.vue'
const q=ref('');const tier=ref('');const customerType=ref('');const items=ref<any[]>([]);const selected=ref<any>(null);const selectedId=ref('');const orders=ref<any[]>([]);const loading=ref(true);const error=ref('');const page=ref(1);const pageSize=ref(10);const total=ref(0);const pages=computed(()=>Math.max(1,Math.ceil(total.value/pageSize.value)))
async function load(){loading.value=true;try{const r=(await profileApi.customers(q.value,tier.value,customerType.value,pageSize.value,(page.value-1)*pageSize.value)).data.data;items.value=r.items;total.value=r.total}catch(e:any){error.value=e.response?.data?.detail||e.message}finally{loading.value=false}}
function search(){page.value=1;load()}function changeSize(n:number){pageSize.value=n;page.value=1;load()}function go(n:number){page.value=Math.min(Math.max(n,1),pages.value);load()}
async function openCustomer(id:string){try{selectedId.value=id;selected.value=(await profileApi.customer(id)).data.data;orders.value=(await tradingApi.customerOrders(id)).data.data}catch(e:any){error.value=e.response?.data?.detail||e.message}}
const tierText:Record<string,string>={ordinary:'零售投资者',gold:'黄金客户',platinum:'白金客户',diamond:'钻石客户',private_bank:'高净值客户'}
onMounted(load)
</script>

<template><section class="table-module"><div class="module-header"><div><span class="module-kicker">CUSTOMER MANAGEMENT</span><h2>客户管理</h2></div><div class="module-tools"><input v-model="q" placeholder="搜索用户名或姓名" @keyup.enter="search"/><select v-model="customerType" @change="search"><option value="">全部客户类型</option><option value="individual">个人客户</option></select><select v-model="tier" @change="search"><option value="">全部层级</option><option value="ordinary">零售投资者</option><option value="gold">黄金客户</option><option value="platinum">白金客户</option><option value="diamond">钻石客户</option><option value="private_bank">高净值客户</option></select><button class="button" @click="search">搜索</button></div></div><p v-if="error" class="error">{{error}}</p><div v-if="loading" class="empty">正在读取客户…</div><div v-else class="module-table-wrap customer-management-table"><table class="admin-table"><thead><tr><th>用户名</th><th>姓名</th><th>投资目标</th><th>总资产</th><th>客户类型</th><th>客户层级</th><th>持仓</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="customer in items" :key="customer.id"><td>{{customer.username}}</td><td>{{customer.display_name}}</td><td>{{customer.profile?.investment_goal||'—'}}</td><td>¥{{customer.latest_asset?.total_asset??0}}</td><td>个人客户</td><td><span class="pill">{{tierText[customer.customer_tier]||customer.customer_tier}}</span></td><td>{{customer.holding_count}}</td><td>{{customer.status}}</td><td><button class="table-action" @click="openCustomer(customer.id)">查看详情</button></td></tr><tr v-if="!items.length"><td colspan="9" class="table-empty">暂无客户</td></tr></tbody></table></div><PaginationBar :page="page" :page-size="pageSize" :total="total" @change="go" @size-change="changeSize"/><div v-if="selected" class="admin-modal-backdrop" @click.self="selected=null"><div class="admin-modal customer-modal"><h3>{{selected.profile?.id ? (items.find(c=>c.id===selectedId)?.display_name||'客户') : '客户'}} · 客户详情</h3><p>客户ID：{{selectedId}}</p><p>总资产：¥{{selected.latest_asset?.total_asset??0}} · 可投资资产：¥{{selected.latest_asset?.investable_asset??0}}</p><h4>画像增强（含对话提取标签）</h4><div class="staff-profile-embed"><ProfileEnhancedView :key="selectedId" :customer-id="selectedId" /></div><h4>订单</h4><table class="admin-table"><thead><tr><th>订单号</th><th>产品</th><th>金额</th><th>状态</th></tr></thead><tbody><tr v-for="o in orders" :key="o.id"><td>{{o.order_no}}</td><td>{{o.product_name||o.product_id}}</td><td>¥{{o.amount}}</td><td>{{o.status}}</td></tr><tr v-if="!orders.length"><td colspan="4" class="table-empty">暂无订单</td></tr></tbody></table><button class="button" @click="selected=null">关闭</button></div></div></section></template>
